name: GoodTechLife
title: GoodTechLife
description: چرا حریم خصوصی مهم است؟
tags:
  - blog
show_hero: true
menu:
  - title: خانه
    url: /
  - title: درباره ما
    url: /about
  - title: ارتباط با ما
    url: /contact
  - title: برچسب ها
    url: /tags
  - title: Feed
    url: /feed.xml
email:
disqus_username:
translations:
  button:
    read_now: بیشتر بخوانید
    share_on_twitter: اشتراک گذاری در توییتر
    share_on_facebook: اشتراک گذاری در فیس بوک
  text:
    minutes_to_read: دقیقه خوانش
    see_also: همچنین بخوانید
    share: به اشتراک بگذارید
    author: ارسال کننده
    menu: منو