name: GoodTechLife
title: GoodTechLife
description: چرا حریم خصوصی مهم است؟
hyvor_username: 440
tags:
  - blog
show_hero: true
menu:
  - title: خانه
    url: /
  - title: درباره ما
    url: /about
  - title: مشارکت با ما
    url: /contributing
  - title: برچسب ها
    url: /tags
  - title: مشارکت کنندگان
    url: /authors
  - title: Feed
    url: /feed.xml
    target: _blank
email:
disqus_username:
translations:
  button:
    read_now: بیشتر بخوانید
    share_on_twitter: اشتراک گذاری در توییتر
    share_on_facebook: اشتراک گذاری در فیس بوک
  text:
    minutes_to_read: دقیقه خواندن
    see_also: همچنین بخوانید
    share: به اشتراک بگذارید
    author: ارسال کننده
    menu: منو
    comments: نظرات

